# Generated by Django 3.1.4 on 2021-01-01 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='farmer',
            fields=[
                ('farmerId', models.AutoField(primary_key=True, serialize=False)),
                ('fname', models.CharField(max_length=30)),
                ('mobile', models.IntegerField()),
                ('village', models.CharField(max_length=50)),
                ('distirct', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=254, null=True)),
                ('crop_type', models.CharField(max_length=20)),
                ('price_need', models.IntegerField()),
            ],
        ),
    ]
