# Generated by Django 3.1.4 on 2021-01-06 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farmer', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='farmer',
            name='crop_image',
            field=models.ImageField(default='', upload_to='farmer/images'),
        ),
        migrations.AddField(
            model_name='farmer',
            name='crop_name',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='farmer',
            name='crop_type',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='farmer',
            name='distirct',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='farmer',
            name='email',
            field=models.EmailField(default='', max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='farmer',
            name='fname',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='farmer',
            name='mobile',
            field=models.IntegerField(default=''),
        ),
        migrations.AlterField(
            model_name='farmer',
            name='price_need',
            field=models.IntegerField(default=''),
        ),
        migrations.AlterField(
            model_name='farmer',
            name='village',
            field=models.CharField(default='', max_length=50),
        ),
    ]
