# Generated by Django 3.1.4 on 2021-01-09 06:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('farmer', '0002_auto_20210106_2335'),
    ]

    operations = [
        migrations.CreateModel(
            name='farmer_info',
            fields=[
                ('farmerId', models.AutoField(primary_key=True, serialize=False)),
                ('fname', models.CharField(default='', max_length=30)),
                ('mobile', models.IntegerField()),
                ('village', models.CharField(max_length=50)),
                ('distirct', models.CharField(max_length=30)),
                ('email', models.EmailField(default='', max_length=254, null=True)),
                ('aadhar_no', models.IntegerField()),
                ('address', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='farmer_product',
            fields=[
                ('productId', models.AutoField(primary_key=True, serialize=False)),
                ('product_name', models.CharField(max_length=20)),
                ('product_special', models.TextField()),
                ('product_type', models.CharField(max_length=20)),
                ('product_rating', models.IntegerField(default=3)),
                ('register_date', models.DateField(auto_now=True)),
                ('product_price', models.IntegerField(default='1000')),
                ('farmer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='farmer.farmer_info')),
            ],
        ),
        migrations.DeleteModel(
            name='farmer',
        ),
    ]
