# Generated by Django 3.1.4 on 2021-01-09 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farmer', '0004_auto_20210109_2047'),
    ]

    operations = [
        migrations.AddField(
            model_name='farmer_info',
            name='password',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='farmer_info',
            name='address',
            field=models.CharField(max_length=50),
        ),
    ]
