# Generated by Django 3.1.4 on 2021-01-09 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farmer', '0005_auto_20210109_2101'),
    ]

    operations = [
        migrations.AddField(
            model_name='farmer_product',
            name='product_image',
            field=models.ImageField(default='', upload_to='farmer/images'),
        ),
    ]
