# Generated by Django 3.1.4 on 2021-01-11 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farmer', '0007_auto_20210111_0111'),
    ]

    operations = [
        migrations.AlterField(
            model_name='farmer_product',
            name='product_image',
            field=models.ImageField(default='', upload_to='farmer/images'),
        ),
    ]
