# Generated by Django 3.1.4 on 2021-03-11 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farmer', '0008_auto_20210111_2242'),
    ]

    operations = [
        migrations.AlterField(
            model_name='farmer_product',
            name='product_image',
            field=models.ImageField(default='', upload_to='media/farmer/images'),
        ),
    ]
