# Generated by Django 3.1.4 on 2020-12-31 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Food', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='id',
        ),
        migrations.AlterField(
            model_name='user',
            name='UserId',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
