# Generated by Django 3.1.4 on 2021-01-09 06:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Food', '0004_auto_20210109_1135'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_cart',
            name='user',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='Food.user_acct'),
        ),
    ]
