# Generated by Django 3.1.4 on 2021-01-09 06:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('farmer', '0003_auto_20210109_1227'),
        ('Food', '0005_user_cart_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user_cart',
            name='product_name',
        ),
        migrations.AddField(
            model_name='user_cart',
            name='product',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='farmer.farmer_product'),
        ),
    ]
