# Generated by Django 3.1.4 on 2021-02-05 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Food', '0009_auto_20210202_2054'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_order',
            name='address',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='user_order',
            name='address1',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='user_order',
            name='city',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='user_order',
            name='state',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='user_order',
            name='zip_code',
            field=models.IntegerField(default=00000),
        ),
    ]
