# Generated by Django 3.1.4 on 2021-02-05 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Food', '0010_auto_20210205_2336'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_order',
            name='zip_code',
            field=models.IntegerField(),
        ),
    ]
