# Generated by Django 3.1.4 on 2021-01-01 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='delivery',
            fields=[
                ('deliveryId', models.AutoField(primary_key=True, serialize=False)),
                ('product_name', models.CharField(max_length=20)),
                ('pickup_date', models.DateTimeField()),
                ('delivery_date', models.DateTimeField()),
                ('delivery_status', models.CharField(max_length=20)),
                ('AgencyId', models.IntegerField()),
                ('delboyId', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='delperson',
            fields=[
                ('delboyId', models.AutoField(primary_key=True, serialize=False)),
                ('delboyname', models.CharField(max_length=20)),
                ('AgencyId', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='transport',
            fields=[
                ('AgencyId', models.AutoField(primary_key=True, serialize=False)),
                ('Aname', models.CharField(max_length=30)),
                ('mobile', models.IntegerField()),
                ('address', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254, null=True)),
                ('pincode', models.IntegerField()),
            ],
        ),
    ]
